---
title: "QTL plots"
author: "Patricka Williams-Simon & ElizabethKing"
date: "7/20/2018"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(reshape)
library(cowplot)
```

#load scan results

```{r}
source(file="../../Functions/ggplot_theme.R")
source(file="../../Functions/mappingfunctions.R")

load(file="../ProcessedData/Lodscores_3traits.rda")
load(file= "../ProcessedData/sig_ths.rda")

load(file="../../LearnMemTolQTL/ProcessedData/myGenos.rda")
Nrils <- nrow(myGenos$phenotype)
rm(myGenos)

#set value for theresholds 
fdr <- min(fdr.out$fdr$threshold[fdr.out$fdr$fdr<=0.05])
fwer <- fdr.out$fwer

pfdr <- getP(fdr,Nrils,7,Nrils-8)
pfwer <- getP(fwer,Nrils,7,Nrils-8)

#get peaks
load(file ="../ProcessedData/Peaks_wCIs.rda")

Learn.peak <- ci.peak[[1]]
Learn.peak$pval <- getP(Learn.peak$LL,Nrils, 7, Nrils-8)

Memory.peak <- ci.peak[[2]]
Memory.peak$pval <- getP(Memory.peak$LL,Nrils, 7, Nrils-8)



ll.set <- c(12,13,14,3,4,6,9,10,11)
mm.set <- c(3,7)
share.set <- cbind(c(1,2,5,7,8),c(1,2,4,5,6))

qns <- paste(rep("Q",16),seq(1,16), sep="")
ps <- c("L","L","L","S","S","M","L","L","S","L","S","S","L","L","M","L")

q.mat <- data.frame("QTL" = qns, "Pheno"=ps, stringsAsFactors = FALSE)
q.mat$Gaxis <- NA
q.mat$LOD <- NA
l.count <- 1
m.count <- 1
s.count <- 1

for(nn in 1:length(qns))
{
  if(ps[nn]=="L")
  {
    q.mat$Gaxis[nn] <- ci.peak[[1]][ll.set[l.count],'Gaxis']
    q.mat$LOD[nn] <- ci.peak[[1]][ll.set[l.count],'LL']
    l.count <- l.count +1
  }
  
  if(ps[nn]=="M")
  {
    q.mat$Gaxis[nn] <- ci.peak[[2]][mm.set[m.count],'Gaxis']
    q.mat$LOD[nn] <- ci.peak[[2]][mm.set[m.count],'LL']
    m.count <- m.count +1
  }
  
  if(ps[nn]=="S")
  {
    ww <- which.max(c(ci.peak[[1]][share.set[s.count,1],'LL'],ci.peak[[2]][share.set[s.count,2],'LL']))
    
    q.mat$Gaxis[nn] <- c(ci.peak[[1]][share.set[s.count,1],'Gaxis'],ci.peak[[2]][share.set[s.count,2],'Gaxis'])[ww]
    
    q.mat$LOD[nn] <- max(ci.peak[[1]][share.set[s.count,1],'LL'],ci.peak[[2]][share.set[s.count,2],'LL'])
    
    s.count <- s.count +1
  }
  
}

q.mat$Pval <- getP(q.mat$LOD,Nrils,7,Nrils-8)

```

#Making qtl plots using ggplot

```{r}

#make dataframe long
obs.LM_long <-gather(obs.LL, key='Trait', value='LOD', LearnPowerTrans, Memory_Mean)
obs.LM_long$Pval <- getP(obs.LM_long$LOD,Nrils,7,Nrils-8)
top <- max(obs.LM_long$Pval)

#plot using ggplot

p1 <- ggplot(obs.LM_long, aes(x=Gaxis, y=Pval, color=Trait)) +
  geom_rect(xmin=66.3,ymin=-10,xmax=120.3,ymax=top+10,fill='aliceblue',color='aliceblue')+
  geom_rect(xmin=174,ymin=-10,xmax=221,ymax=top+10,fill='aliceblue',color='aliceblue')+
    geom_segment(x=-50, xend=275,y=pfdr,yend=pfdr, color='grey30', size=line.ww) +
  annotate("text",label= "FDR", x=295, y=pfdr, color='grey30',size=3) +
  annotate("text",label= "FWER", x=295, y=pfwer, color='grey30',size=3) +
  geom_segment(x=-50, xend=275,y=pfwer,yend=pfwer, color='grey30', size=line.ww, lty=3) +
  geom_line(alpha=0.6, size=line.ww) +
  geom_point(data = q.mat, aes(x=Gaxis, y=Pval+0.5), pch = 25, color="grey50", fill = "grey50") +
  geom_text(data=q.mat, mapping=aes(x=Gaxis, y=Pval+1, label = QTL), size=3, color="grey50")+
  scale_x_continuous(breaks=c(0,66.3,120,174,221,277,33.15,98.3,145,205,249), 
                     labels=c(0,"66  0",54,"108  0",47,103,'\nX','\n2L','\n2R','\n3L','\n3R'),limits = c(-0.01,max(obs.LM_long$Gaxis)+25))+
  
  theme(axis.ticks.x=element_blank())+
  ylab(expression("-log"[10]*"(P-value)"))+
  xlab("Position (cM)") +
  scale_color_discrete(name='Phenotype',breaks=c('LearnPowerTrans','Memory_Mean'), labels=c('Learning','Memory'))+
  my_theme

ggsave(p1, filename = "../Plots/L_M_QTL.pdf", height=3,width=7)

```


